# Python Exercises - Granger's Elf Analysis

Dr. Granger is interested in studying the relationship between the length of house-elves’ ears and aspects of their DNA. This research is part of a larger project attempting to understand why house-elves possess such powerful magic. She has obtained DNA samples and ear measurements from a small group of house-elves to conduct a preliminary analysis (prior to submitting a grant application to the Ministry of Magic) and she would like you to conduct the analysis for her. She has placed the file on the web for you to download, located ==> [here](https://nyu-cds.github.io/courses/data/houseelf_earlength_dna_data.csv) <==.

You might be able to do this analysis by hand in Excel, but counting all of those bases would be a lot of work, and besides, Dr. Granger seems to always get funded, which means that you’ll be doing this again soon with a much larger dataset. So, you decide to write a script so that it will be easy to do the analysis again.

Write a Python script that:

1. Imports the data into a data frame
2. Loops over the rows in the data frame
3. For each row in the dataset, checks to see if the ear length is large (>10 cm) or small (<=10 cm) and determines the GC-content of the DNA sequence (i.e., the percentage of bases that are either G or C)
4. Stores this information in a **new data frame** where the first column has the ID for the individual, the second column contains the string ‘large’ or the string ‘small’ depending on the size of the individuals ears, and the third column contains the GC content of the DNA sequence.
5. Prints the average GC-content for both large-eared elves and small-eared elves to the screen.
6. Exports the table of individual level GC values to a CSV (comma delimited text) file titled grangers_analysis.csv.

**BONUS**: Write functions that perform each of the steps above

[Source for problem](https://nyu-cds.github.io/courses/exercises/Basic-python-2/)

# Solution - variant 1

In [14]:
#Imports the data into a data frame
import pandas as pd

df = pd.read_csv('https://nyu-cds.github.io/courses/data/houseelf_earlength_dna_data.csv')
df.head()

    id  earlength                                             dnaseq
0  17A        5.1  CCGCATCTTGACTTAACTGACATATTACCATAGATGACTAGCCATG...
1  24P        7.5  GCTATGACTTGCTTAGCTACGTATGAAGGAAGAAACTTTTGTGTAT...
2  09Q       12.2  CCGCCGATTGATACAGGGGACGGTGACGTCGTCATAGATTCGGCAC...
3  65Y        9.9  GCAGGAGAAGTTCTTAACCTTCTCGTAGGACGTCAACCTATTCTTT...
4  19N       10.0  TCTTCATCCTTATCAAAGTTTGGAGTCAATGATCAGGATTATTGCC...

In [15]:
#Loops over the rows in the data frame
results = []

for _, row in df.iterrows():

  #Determine ear size
  if row['earlength'] > 10:
    ear_size = 'large'
  else:
    ear_size = 'small'

  #Calculate GC content
  dna = row['dnaseq']
  gc_count = dna.count('G') + dna.count('C')
  gc_content = (gc_count / len(dna)) * 100

  #Store results
  results.append({
      'ID': row['id'],
      'Ear Size': ear_size,
      'GC Content': gc_content
  })

#Convert results into DataFrame
results_df = pd.DataFrame(results)

In [16]:
#5 Print average GC content
large_average = results_df[results_df["Ear Size"] == "large"]["GC Content"].mean()
small_average = results_df[results_df["Ear Size"] == "small"]["GC Content"].mean()

print(f"Average GC-content (large ears): {large_average:.2f}%")
print(f"Average GC-content (small ears): {small_average:.2f}%")

Average GC-content (large ears): 58.50%
Average GC-content (small ears): 42.50%

In [18]:
#6 Export results to csv
results_df.to_csv("grangers_analysis.csv", index=False)
results_df

    ID Ear Size  GC Content
0  17A    small        41.0
1  24P    small        39.0
2  09Q    large        57.0
3  65Y    small        40.0
4  19N    small        36.0
5  92K    large        62.0
6  33W    small        52.0
7  98C    large        63.0
8  75G    small        47.0
9  88Q    large        52.0

# Solution - variant 2

In [21]:
import pandas as pd

#1 Import data into df
df = pd.read_csv('https://nyu-cds.github.io/courses/data/houseelf_earlength_dna_data.csv')

#2a Store results
results = []

#2b Loop over rows
for _, row in df.iterrows():

  #3a Determine ear size
  if row['earlength'] > 10:
    ear_size = 'large'
  else:
    ear_size = 'small'

  #3b Calculate GC content
  dna = row['dnaseq']
  gc_count = dna.count('G') + dna.count('C')
  gc_content = (gc_count / len(dna)) * 100

  #4a Store results
  results.append({
    'ID': row['id'],
    'Ear Size': ear_size,
    'GC Content': gc_content
  })

#4b Convert results into df
results_df = pd.DataFrame(results)

#5 Print avg GC content
large_avg = results_df[results_df['Ear Size'] == 'large']['GC Content'].mean()
small_avg = results_df[results_df['Ear Size'] == 'small']['GC Content'].mean()

print(f'Avg GC-content (large ears): {large_average:.2f}%')
print(f'Avg GC-content (small ears): {small_average:.2f}%')
print()

#6 Export results to CSV
results_df.to_csv('grangers_analysis.csv', index=False)
print(results_df)

Avg GC-content (large ears): 58.50%
Avg GC-content (small ears): 42.50%

    ID Ear Size  GC Content
0  17A    small        41.0
1  24P    small        39.0
2  09Q    large        57.0
3  65Y    small        40.0
4  19N    small        36.0
5  92K    large        62.0
6  33W    small        52.0
7  98C    large        63.0
8  75G    small        47.0
9  88Q    large        52.0

# Solution - variant 3

In [22]:
import pandas as pd

def magic(url):

    #1 Import
    df = pd.read_csv(url)

    #4a Store
    results = []

    #2 Loop
    for _, row in df.iterrows():

      #3 Determine ear size
      if row['earlength'] > 10:
        ear_size = 'large'
      else:
        ear_size = 'small'

      #3a Calculate GC content
      dna = row['dnaseq']
      gc_count = dna.count('G') + dna.count('C')
      gc_content = (gc_count / len(dna)) * 100

      #3b Store results
      results.append({
        'ID': row['id'],
        'Ear Size': ear_size,
        'GC Content': gc_content
      })

    #4b Convert into DataFrame
    results_df = pd.DataFrame(results)

    #5 Print Averages
    large_avg = results_df[results_df['Ear Size'] == 'large']['GC Content'].mean()
    small_avg = results_df[results_df['Ear Size'] == 'small']['GC Content'].mean()

    print(f'Avg GC-content (large ears): {large_avg:.2f}%')
    print(f'Avg GC-content (small ears): {small_avg:.2f}%')
    print()

    #6 Export results
    results_df.to_csv('grangers_analysis.csv', index=False)

    print(results_df)

    return results_df


#Run function
results_df = magic('https://nyu-cds.github.io/courses/data/houseelf_earlength_dna_data.csv')

Avg GC-content (large ears): 58.50%
Avg GC-content (small ears): 42.50%

    ID Ear Size  GC Content
0  17A    small        41.0
1  24P    small        39.0
2  09Q    large        57.0
3  65Y    small        40.0
4  19N    small        36.0
5  92K    large        62.0
6  33W    small        52.0
7  98C    large        63.0
8  75G    small        47.0
9  88Q    large        52.0